# Generated by Django 5.2.13 on 2026-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('todo', 'TO DO'), ('in_progress', 'IN PROGRESS'), ('done', 'DONE')], default='todo', max_length=15)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
